language: java
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: OD4k7nqSQccRRZykyZEPmYaRNJfLNG8gGiWltmdgVSITlHUv2P4bn+eRFK5uimg9nrd5usx1DhixoNOp1mhVDbVMYIG+suxW3SQnCtcmoH9JeSSpKi8rgWEluuWC2xlXkyALJHs6SpSXa9iZ7k7CBvGu5033z5pSQIyGgC7UFYE4vaZyoFechLyVRgD1lTgf7a+Vv/8tDoqRcy3srfQKRmZucJV6RVRzC32vnBxYVyfvMVsF4r8qlD7JZQgw/IhTDDwPSk5AkSLX0++PcbONRUI9bfBNedz/eAKCr/hNQ3AnzeA2z9zkp/LIyFp4kT9sqFbmcLVqnZywlFp1HXkdHufM//Q5IRTm1kxV3pL+oVtJApplA0774Fbc251GLOf2lEcbJGao4Df2E2SeSrAuZcPcD7ijG/aDO/rtIk8SBmoQCj1qqr14v/6QoFF5ugAJBEV3/OtdX4VbYYafeUpmli6vOHjn8XQ4ntjA986rWGYOhZzQuWdo0oPsAz2k19MS2IER5pS8tvB/1EozKYdkWYB/z64DFGl6oNwnQaX+46z7LPyIHb21R0v5zqckwnp6e5DPcxqorluC+3Ghv8WWz1jLKovLTQpfMHMhK1ussOkKDqjB//bUb8VX5TvfWVoGG5EMpAf5YOI6xOHyX4YrLOeqptXZRpnmGBNPFtRSXKI=
